package cafe.shop.data.source;
// Generated Nov 24, 2017 5:00:00 AM by Hibernate Tools 4.3.1

import java.util.logging.Level;
import java.util.logging.Logger;




/**
 * MakeOrder generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private String price;
     private String billType;

    public Orders() {
         try {
             ConnectionManager.setConfigFile("hibernate.cfg.xml");
         } catch (Exception ex) {
             Logger.getLogger(Orders.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    public Orders(int id, String name, String description, String price, String billType) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.price = price;
       this.billType = billType;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getBillType() {
        return this.billType;
    }
    
    public void setBillType(String billType) {
        this.billType = billType;
    }




}


